# Generated by Django 5.0.7 on 2024-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок объявления')),
                ('author', models.CharField(max_length=200, verbose_name='Автор объявления')),
                ('views', models.IntegerField(verbose_name='Количество просмотров')),
                ('position', models.IntegerField(verbose_name='Позиция на сайте')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
